### PR TITLE
Fix all translations

### PR DESCRIPTION
**Pull request by sheilagomes**
Review and fix all translations. Tracked in task [LOC-16956](https://vtex-dev.atlassian.net/browse/LOC-16956)

[LOC-16956]: https://vtex-dev.atlassian.net/browse/LOC-16956?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by salesfelipe — APPROVED** [review]

**Review by GeorgeLimaDev — APPROVED** [review]
LGTM 🚀

**Comment by salesfelipe** [comment]
Did you rebase or merged with the latest master?

**Comment by sheilagomes** [comment]
> Did you rebase or merged with the latest master?

I did, but I think I inverted the order and pulled from the PR befopre the master, I'm sorry, my bad.

**Comment by salesfelipe** [comment]
Closed in favor of https://github.com/vtex-apps/search-result/pull/687

**Comment by salesfelipe** [comment]
https://github.com/vtex-apps/search-result/pull/687

**Pull request closed without merging**
